# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valuesreceived',
            options={'verbose_name': 'Values Received', 'verbose_name_plural': 'Values Received'},
        ),
        migrations.AlterField(
            model_name='valuesreceived',
            name='value_type',
            field=models.CharField(choices=[('NO', 'Noise'), ('TE', 'Temperature'), ('LE', 'Led')], max_length=2),
        ),
    ]
